teacher = Teacher.create(username: "test_yogi", password: "%!#n'v'P(q4hR@[N%", email: "yogi@asana.com")
Lesson.create!(title: "Test 1", lesson_type: "Vinyasa", teacher_id: 1)
Lesson.create!(title: "Test 2", lesson_type: "Deep Stretch", teacher_id: 1)
Lesson.create!(title: "Test 3", lesson_type: "Gentle", teacher_id: 1)
Lesson.create!(title: "Test 4", lesson_type: "Yin", teacher_id: 1)
Lesson.create!(title: "Test 5", lesson_type: "Restorative", teacher_id: 1)
Lesson.create!(title: "Test 6", lesson_type: "Meditation", teacher_id: 1)
Lesson.create!(title: "Test 7", lesson_type: "Prenatal", teacher_id: 1)
Lesson.create!(title: "Test 8", lesson_type: "Kids", teacher_id: 1)
Lesson.create!(title: "Test 9", lesson_type: "Workshop", teacher_id: 1)
Lesson.create!(title: "Test 10", lesson_type: "Other", teacher_id: 1)
